# Generated by Django 5.2.4 on 2025-08-07 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='contents/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png'])]),
        ),
    ]
