# Generated by Django 5.2.4 on 2025-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_published_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Статус публикации'),
        ),
    ]
