# Generated by Django 5.2.4 on 2025-08-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок поста')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст поста')),
                ('preview', models.ImageField(upload_to='contents/image')),
                ('is_public', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('views_counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['title'],
            },
        ),
    ]
